version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - db-volume:/var/lib/mysql
    ports:
      - 8306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
  web:
    build: .
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "7000:7000"
    depends_on:
      - db
    tty: true
    stdin_open: true
    entrypoint:
      - sleep
    command:
      - "1000000000"
volumes:
  db-volume:
